### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by ThomasG77** [sombriks/vue-openlayers#1]
When I visit https://sombriks.github.io/vue-openlayers, nothing is shown and there are no error in the browser dev tools console

Tested both on Firefox and Chrome on Ubuntu 16.04 - 64 bits

The issue seems to be in the missing links. Using local dev mode or local build, I get the following
![selection_591](https://cloud.githubusercontent.com/assets/642120/23038501/8a5a9eec-f48a-11e6-8cc2-d833d87c33d8.png)

whereas on your demo link I get this image

![selection_592](https://cloud.githubusercontent.com/assets/642120/23038531/adaf266a-f48a-11e6-88d7-fe2a5bee12d9.png)

**Comment by sombriks** [comment]
Hello @ThomasG77 indeed it was a typo!
https://sombriks.github.io/vue-openlayers

hope it works now.

thank you and congratz for the very first issue on this project!

**Comment by ThomasG77** [comment]
It works. Thanks you for taking time to fix the issue.
