### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by Pezhin** [sombriks/vue-openlayers#3]
I am very new to JS/Vue

I tried to use this library but it doesn't work directly 

can you try to write a simple document for using this library?

**Comment by sombriks** [comment]
Hello @Pezhin !

i am working currently on the roadmap for this lib.

for the moment i need to plan the future steps, however it does work well with browserify.

if you're not using any module bundler (webpack, rollup  or browserify) you can simply take the .vue files from src directory and see on main.js how to register it on vue.

next release will offer better cover on how to use the lib.

you can see it working in the [demo page](https://sombriks.github.io/vue-openlayers/#/marker)
